# Starter pipeline
- task: S3Upload@1
  inputs:
    awsCredentials: 'aws-toolkit-serviceconn'
    regionName: 'us-west-2'
    bucketName: 'azure-devops-s3-upload'
    globExpressions: '**'
    createBucket: true
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
